project_id = "muvornzsnhncihxawntz"

[functions.admin-get-users]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.fipe-lookup]
verify_jwt = false

[functions.ze-ia-chat]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-document-status-email]
verify_jwt = false

[functions.send-account-approved-email]
verify_jwt = false
